# Generated by Django 5.0.4 on 2025-09-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(default='Untitled', max_length=200),
            preserve_default=False,
        ),
    ]
