# Generated by Django 5.2.6 on 2025-09-23 10:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
